name: Update SUMMARY.md test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update SUMMARY.md
        run: |
          # Get the list of markdown files in the src directory and its subdirectories
          FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/git/trees/${{ github.event.pull_request.head.sha }}?recursive=1" | jq -r '.tree[] | select(.type == "blob" and .path | startswith("src/") and .path | endswith(".md")) | .path')

          # Update SUMMARY_test.md
          echo "# Summary" > SUMMARY_test.md
          for FILE in $FILES; do
            echo "- [${FILE#src/}]($FILE)" >> SUMMARY_test.md
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add SUMMARY.md
          git commit -m "Update SUMMARY.md" || echo "No changes to commit"
          git push origin ${{ github.event.pull_request.head.ref }} || echo "No changes to push"
