name: Update SUMMARY.md test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update SUMMARY.md
        run: |
          # Get the list of markdown files in the src directory and its subdirectories
          FILES=$(curl -s -H "Authorization: token ***" "https://api.github.com/repos/tec-devs-2024/wiki/git/trees/47037755e145bb71c41c7885c07ee8427aaa7df2?recursive=1" | jq -r 'if .tree then .tree[] | select(.type == "blob" and (.path | type == "string") and .path | startswith("src/") and .path | endswith(".md") and .path != "src/SUMMARY.md") | .path else empty end')

          # Update SUMMARY.md in the src folder
          echo "# Summary" > src/SUMMARY_test.md
          for FILE in $FILES; do
          echo "- [${FILE#src/}]($FILE)" >> src/SUMMARY_test.md
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/SUMMARY.md
          git commit -m "Update SUMMARY.md" || echo "No changes to commit"
          git push origin ${{ github.event.pull_request.head.ref }} || echo "No changes to push"
